// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARg9WbD7uWJj9drXuZD6csGJn_UTXZ6eQ',
    appId: '1:623258199898:web:5bde4efb40293504a8f563',
    messagingSenderId: '623258199898',
    projectId: 'aidlink-ec749',
    authDomain: 'aidlink-ec749.firebaseapp.com',
    storageBucket: 'aidlink-ec749.firebasestorage.app',
    measurementId: 'G-Q99T9PDF1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk53DRjgnYE7wj95csxNZSzie4GpD0jqY',
    appId: '1:623258199898:android:ae3190f2c8567731a8f563',
    messagingSenderId: '623258199898',
    projectId: 'aidlink-ec749',
    storageBucket: 'aidlink-ec749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6Eh9GfvhSkvQ4UJbdBocxMnJe9PqzV8',
    appId: '1:623258199898:ios:1480fd7f8b8dbbaca8f563',
    messagingSenderId: '623258199898',
    projectId: 'aidlink-ec749',
    storageBucket: 'aidlink-ec749.firebasestorage.app',
    iosClientId: '623258199898-5eqo9fbgvmg8km11g4cf3iebcd4k4smr.apps.googleusercontent.com',
    iosBundleId: 'com.aidlink.aidlinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6Eh9GfvhSkvQ4UJbdBocxMnJe9PqzV8',
    appId: '1:623258199898:ios:1480fd7f8b8dbbaca8f563',
    messagingSenderId: '623258199898',
    projectId: 'aidlink-ec749',
    storageBucket: 'aidlink-ec749.firebasestorage.app',
    iosClientId: '623258199898-5eqo9fbgvmg8km11g4cf3iebcd4k4smr.apps.googleusercontent.com',
    iosBundleId: 'com.aidlink.aidlinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARg9WbD7uWJj9drXuZD6csGJn_UTXZ6eQ',
    appId: '1:623258199898:web:85609f9934c9e582a8f563',
    messagingSenderId: '623258199898',
    projectId: 'aidlink-ec749',
    authDomain: 'aidlink-ec749.firebaseapp.com',
    storageBucket: 'aidlink-ec749.firebasestorage.app',
    measurementId: 'G-32162SZV26',
  );

}