import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final appLocaleProvider = StateProvider<Locale>((ref) => const Locale('en'));

class AppLocalizations {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'AidLink',
      'welcome': 'Welcome',
      'greeting': 'Hello',
      'welcome_back': 'Welcome back. Let’s continue with verified help.',
      'login': 'Login',
      'register': 'Create account',
      'register_prompt': 'Create a real profile and start helping today.',
      'create_account': 'Create account',
      'sign_in': 'Sign in',
      'sign_up': 'Sign up',
      'already_have_account': 'Already have an account?',
      'get_started': 'Get started',
      'phone': 'Phone number',
      'otp': 'Verification code',
      'otp_required': 'Enter the verification code',
      'send_code': 'Send verification code',
      'verify_and_sign_in': 'Verify & sign in',
      'verify_and_sign_up': 'Verify & create account',
      'name': 'Full name',
      'password': 'Password',
      'password_optional': 'Password (optional)',
      'confirm_password': 'Confirm password',
      'email': 'Email',
      'email_optional': 'Email (optional)',
      'email_required': 'Email is required',
      'country_code': 'Country code',
      'role': 'Role',
      'seeker': 'Aid seeker',
      'donor': 'Aid provider',
      'org_rep': 'Organization rep',
      'role_org_desc': 'Manage verified requests and field operations.',
      'continue': 'Continue',
      'logout': 'Log out',
      'new_request': 'New request',
      'urgent_food': 'URGENT - MUST BE GIVEN TODAY',
      'perishable_food': 'Perishable food',
      'deadline': 'Deadline',
      'expiry_time': 'Expiry time',
      'urgency': 'Urgency',
      'quantity': 'Quantity',
      'description': 'Description',
      'submit_request': 'Submit request',
      'confirm_receipt': 'Confirm receipt',
      'offer_aid': 'Offer aid',
      'availability': 'Availability time',
      'notes_optional': 'Notes (optional)',
      'no_requests': 'No requests available yet.',
      'no_offers': 'No offers yet.',
      'my_requests': 'My requests',
      'browse_requests': 'Browse requests',
      'impact_history': 'Impact history',
      'status_timeline': 'Status timeline',
      'urgent_food_help': 'Urgent food',
      'language': 'Language',
      'profile': 'Profile',
      'update_profile': 'Update profile',
      'verification_pending': 'Verification pending',
      'status': 'Status',
      'all': 'All',
      'due': 'Due',
      'deadline_required': 'Deadline is required for food requests.',
      'no_notifications': 'No notifications yet.',
      'mark_all_read': 'Mark all read',
      'notification_new': 'New',
      'onboarding_welcome_title': 'Welcome to AidLink',
      'onboarding_welcome_body': 'A respectful way to request and offer help.',
      'onboarding_request_title': 'Request help with dignity',
      'onboarding_request_body': 'Share your needs clearly and safely.',
      'onboarding_help_title': 'Offer real help',
      'onboarding_help_body': 'Find nearby requests and respond fast.',
      'onboarding_trust_title': 'Transparency & trust',
      'onboarding_trust_body': 'Verified needs and honest updates.',
      'continue_with_otp': 'Continue with phone OTP',
      'forgot_password': 'Forgot password?',
      'toggle_dark_mode': 'Dark mode',
      'provide_email_or_phone': 'Provide email or phone',
      'invalid_email': 'Invalid email',
      'min_password': 'Minimum 6 characters',
      'passwords_mismatch': 'Passwords do not match',
      'auth_error': 'Unable to sign in. Please try again.',
      'unknown_user': 'Unknown user',
      'not_available': 'Not available',
      'language_amharic': 'Amharic',
      'language_english': 'English',
      'no_received_aid_yet': 'No received aid yet',
      'aid_arrives_here': 'Aid you receive will appear here.',
      'admin_tools_desc': 'Verification and reports appear here.',
      'about_us': 'About us',
      'about_title': 'AidLink',
      'about_tagline': 'Connecting verified needs with real help.',
      'about_mission_title': 'Our mission',
      'about_mission_body': 'AidLink helps communities request and offer support with dignity, speed, and transparency.',
      'about_values_title': 'Our values',
      'about_value_dignity': 'Dignity-first support',
      'about_value_trust': 'Trust and transparency',
      'about_value_speed': 'Fast, coordinated response',
      'about_contact_title': 'Contact',
      'about_contact_body': 'Reach us at support@aidlink.org for partnerships and support.',
      'feedback': 'Feedback',
      'feedback_prompt': 'Tell us what is working and what needs to improve.',
      'feedback_message': 'Your message',
      'feedback_message_hint': 'Please add a few details (at least 8 characters).',
      'feedback_rating': 'Rating',
      'feedback_sent': 'Thanks for your feedback!',
      'feedback_error': 'Could not send feedback. Please try again.',
      'category': 'Category',
      'category_general': 'General',
      'category_bug': 'Bug report',
      'category_feature': 'Feature request',
      'submit': 'Submit',
      'dashboard': 'Dashboard',
      'home': 'Home',
      'requests_tab': 'Requests',
      'notifications_tab': 'Notifications',
      'profile_tab': 'Profile',
      'admin_login': 'Admin login',
      'admin_portal': 'Admin portal',
      'admin_portal_desc': 'Admins sign in with approved accounts.',
      'settings': 'Settings',
      'notifications_settings': 'Push and in-app alerts',
      'change_password': 'Change password',
      'edit_profile': 'Edit profile',
      'location': 'Location',
      'location_required': 'Location is required',
      'organization_name': 'Organization name',
      'organization_name_required': 'Organization name is required',
      'organization_id': 'Registration ID',
      'organization_id_required': 'Registration ID is required',
      'household_size': 'Household size',
      'donation_focus': 'Donation focus',
      'my_offers': 'My offered aid',
      'urgent_aid': 'Urgent aid nearby',
      'explore_aid_types': 'Explore aid types',
      'see_nearby': 'See nearby needs',
      'choose_role': 'Choose your role',
      'role_explainer': 'Select how you want to use AidLink today.',
      'role_seeker_desc': 'Request essential support with dignity.',
      'role_donor_desc': 'Offer help and respond to urgent needs.',
      'role_admin_desc': 'Verify requests and coordinate aid.',
      'choose_role_first': 'Choose a role to continue.',
      'continue_with_google': 'Continue with Google',
      'enable_biometrics': 'Enable biometric sign-in on this device',
      'use_biometrics': 'Use biometrics to sign in',
      'donor_header_subtitle': 'See urgent needs and offer help quickly.',
      'seeker_header_subtitle': 'Track your requests and receive updates.',
      'impact_snapshot': 'Impact snapshot',
      'total_requests': 'Total requests',
      'urgent_requests': 'Urgent requests',
      'nearby_requests': 'Requests near you',
      'recent_requests': 'Recent requests',
      'no_urgent_requests': 'No urgent requests right now',
      'my_activity': 'My activity',
      'active_requests': 'Active requests',
      'no_active_requests': 'No active requests yet',
      'create_request_cta': 'Create a request',
      'seeker_dashboard': 'Aid Seeker Dashboard',
      'donor_dashboard': 'Aid Provider Dashboard',
      'admin_dashboard': 'Admin Dashboard',
      'request_types': 'Request types',
      'pending_support': 'Pending support',
      'delivery_pickup': 'Pickup',
      'delivery_dropoff': 'Delivery',
      'filters': 'Filters',
      'history': 'History',
      'urgent_actions': 'Urgent actions',
      'admin_tools': 'Admin tools',
      'audit_log': 'Audit log',
      'status_draft': 'Draft',
      'status_submitted': 'Submitted',
      'status_verified': 'Verified',
      'status_matched': 'Matched',
      'status_in_progress': 'In progress',
      'status_completed': 'Completed',
      'aid_food': 'Food',
      'aid_clothing': 'Clothing',
      'aid_medical': 'Medical',
      'aid_cash': 'Cash',
      'aid_school': 'School',
      'aid_housing': 'Housing',
      'aid_ceremony': 'Ceremony support',
      'aid_other': 'Other',
    },
    'am': {
      'app_name': 'ኤይድሊንክ',
      'welcome': 'እንኳን ደህና መጡ',
      'greeting': 'ሰላም',
      'welcome_back': 'እንኳን እንደገና ደህና መጡ። በተረጋገጠ እርዳታ ይቀጥሉ።',
      'login': 'ግባ',
      'register': 'መመዝገብ',
      'register_prompt': 'እውነተኛ መገለጫ ፍጠር እና ዛሬ እርዳታ ጀምር።',
      'create_account': 'መመዝገብ',
      'sign_in': 'ግባ',
      'sign_up': 'መመዝገብ',
      'already_have_account': 'መለያ አለዎት?',
      'get_started': 'ጀምር',
      'phone': 'ስልክ ቁጥር',
      'otp': 'የማረጋገጫ ኮድ',
      'otp_required': 'የማረጋገጫ ኮድ ያስገቡ',
      'send_code': 'የማረጋገጫ ኮድ ላክ',
      'verify_and_sign_in': 'ኮድ አረጋግጥ እና ግባ',
      'verify_and_sign_up': 'ኮድ አረጋግጥ እና መመዝገብ',
      'name': 'ሙሉ ስም',
      'password': 'የይለፍ ቃል',
      'password_optional': 'የይለፍ ቃል (አማራጭ)',
      'confirm_password': 'የይለፍ ቃል ደግሞ',
      'email': 'ኢሜል',
      'email_optional': 'ኢሜል (አማራጭ)',
      'email_required': 'ኢሜል ያስፈልጋል',
      'country_code': 'የአገር ኮድ',
      'role': 'ሚና',
      'seeker': 'እርዳታ ፈላጊ',
      'donor': 'እርዳታ አቅራቢ',
      'org_rep': 'ድርጅት ተወካይ',
      'role_org_desc': 'የተረጋገጡ ጥያቄዎችን እና የስራ መድረኮችን ያስተዳድሩ።',
      'continue': 'ቀጥል',
      'logout': 'ውጣ',
      'new_request': 'አዲስ ጥያቄ',
      'urgent_food': 'አስቸኳይ - ዛሬ መስጠት አለበት',
      'perishable_food': 'ፈጣን ሚያበላሸው ምግብ',
      'deadline': 'የመጨረሻ ጊዜ',
      'expiry_time': 'የጊዜ ገደብ',
      'urgency': 'አስቸኳይነት',
      'quantity': 'መጠን',
      'description': 'መግለጫ',
      'submit_request': 'ጥያቄ ላክ',
      'confirm_receipt': 'ተቀብለው አረጋግጥ',
      'offer_aid': 'እርዳታ አቅርብ',
      'availability': 'የተገኙበት ጊዜ',
      'notes_optional': 'ማስታወሻ (አማራጭ)',
      'no_requests': 'አሁን ምንም ጥያቄ የለም።',
      'no_offers': 'አሁን ምንም አቅርቦት የለም።',
      'my_requests': 'ጥያቄዬ',
      'browse_requests': 'ጥያቄዎች ይመልከቱ',
      'impact_history': 'የእርዳታ ታሪክ',
      'status_timeline': 'የሁኔታ ቅደም ተከተል',
      'urgent_food_help': 'አስቸኳይ ምግብ',
      'language': 'ቋንቋ',
      'profile': 'መገለጫ',
      'update_profile': 'መገለጫ አዘምን',
      'verification_pending': 'ማረጋገጫ በመጠባበቅ ላይ',
      'status': 'ሁኔታ',
      'all': 'ሁሉም',
      'due': 'መጨረሻ',
      'deadline_required': 'ለምግብ ጥያቄ መጨረሻ ጊዜ አስፈላጊ ነው።',
      'no_notifications': 'አሁን ምንም ማስታወቂያ የለም።',
      'mark_all_read': 'ሁሉንም እንደተነበበ አድርግ',
      'notification_new': 'አዲስ',
      'onboarding_welcome_title': 'እንኳን ወደ ኤይድሊንክ በደህና መጡ',
      'onboarding_welcome_body': 'እርዳታን በክብር ለመጠየቅ እና ለመስጠት።',
      'onboarding_request_title': 'እርዳታ በክብር ጠይቅ',
      'onboarding_request_body': 'ፈላጊነትዎን ግልጽ እና ደህንነት ላይ ያቅርቡ።',
      'onboarding_help_title': 'እውነተኛ እርዳታ ስጥ',
      'onboarding_help_body': 'ቅርብ ያሉ ጥያቄዎችን ፈጥነህ መርዳት።',
      'onboarding_trust_title': 'ታማኝነት እና ግልጽነት',
      'onboarding_trust_body': 'የተረጋገጡ ጥያቄዎች እና ትክክለኛ ማሳወቂያዎች።',
      'continue_with_otp': 'በOTP ቀጥል',
      'forgot_password': 'የይለፍ ቃል ረሳሁ?',
      'toggle_dark_mode': 'ጨለማ ሁነታ',
      'provide_email_or_phone': 'ኢሜል ወይም ስልክ ያስገቡ',
      'invalid_email': 'የማይሰራ ኢሜል',
      'min_password': 'ቢያንስ 6 ፊደል',
      'passwords_mismatch': 'የይለፍ ቃል አይጣጣም',
      'auth_error': 'መግባት አልተሳካም። እባክዎ ደግመው ይሞክሩ።',
      'unknown_user': 'ያልታወቀ ተጠቃሚ',
      'not_available': 'አልተገኘም',
      'language_amharic': 'አማርኛ',
      'language_english': 'እንግሊዝኛ',
      'no_received_aid_yet': 'እስካሁን የተቀበለ እርዳታ የለም',
      'aid_arrives_here': 'ሲደርስ እርዳታ እዚህ ይታያል።',
      'admin_tools_desc': 'ማረጋገጫ እና ሪፖርቶች እዚህ ይታያሉ።',
      'about_us': 'ስለ እኛ',
      'about_title': 'ኤይድሊንክ',
      'about_tagline': 'የተረጋገጡ ፍላጎቶችን ከእውነተኛ እርዳታ ጋር የሚያገናኝ።',
      'about_mission_title': 'ተልዕኮአችን',
      'about_mission_body':
          'ኤይድሊንክ ማህበረሰቦች እርዳታን በክብር፣ በፍጥነት እና በግልጽነት እንዲጠይቁ እና እንዲሰጡ ያግዛል።',
      'about_values_title': 'እሴቶቻችን',
      'about_value_dignity': 'በክብር የሚመራ እርዳታ',
      'about_value_trust': 'ታማኝነት እና ግልጽነት',
      'about_value_speed': 'ፈጣን እና ተደራሽ ምላሽ',
      'about_contact_title': 'እኛን ያግኙ',
      'about_contact_body': 'ለመተባበር ወይም ድጋፍ በsupport@aidlink.org ይጻፉ።',
      'feedback': 'አስተያየት',
      'feedback_prompt': 'የሚሰራውን እና መሻሻል የሚፈልገውን ይንገሩን።',
      'feedback_message': 'መልዕክትዎ',
      'feedback_message_hint': 'ቢያንስ 8 ፊደል ያስገቡ።',
      'feedback_rating': 'ደረጃ',
      'feedback_sent': 'ለአስተያየትዎ እናመሰግናለን!',
      'feedback_error': 'አስተያየት ማቅረብ አልተሳካም። ደግመው ይሞክሩ።',
      'category': 'ምድብ',
      'category_general': 'አጠቃላይ',
      'category_bug': 'ስህተት ሪፖርት',
      'category_feature': 'አዲስ ባህሪ',
      'submit': 'ላክ',
      'dashboard': 'ዳሽቦርድ',
      'home': 'መነሻ',
      'requests_tab': 'ጥያቄዎች',
      'notifications_tab': 'ማስታወቂያዎች',
      'profile_tab': 'መገለጫ',
      'admin_login': 'የአስተዳዳሪ ግባ',
      'admin_portal': 'የአስተዳዳሪ መግቢያ',
      'admin_portal_desc': 'አስተዳዳሪዎች በተፈቀደ መለያ ይግቡ።',
      'settings': 'ቅንብሮች',
      'notifications_settings': 'የፑሽ እና ውስጣዊ ማስታወቂያዎች',
      'change_password': 'የይለፍ ቃል ቀይር',
      'edit_profile': 'መገለጫ አስተካክል',
      'location': 'አካባቢ',
      'location_required': 'አካባቢ ያስፈልጋል',
      'organization_name': 'የድርጅት ስም',
      'organization_name_required': 'የድርጅት ስም ያስፈልጋል',
      'organization_id': 'የመመዝገቢያ መለያ',
      'organization_id_required': 'የመመዝገቢያ መለያ ያስፈልጋል',
      'household_size': 'የቤተሰብ ብዛት',
      'donation_focus': 'የእርዳታ ልምድ',
      'my_offers': 'የሰጠሁት እርዳታ',
      'urgent_aid': 'ቅርብ አስቸኳይ እርዳታ',
      'explore_aid_types': 'የእርዳታ ዓይነቶች',
      'see_nearby': 'ቅርብ ፍላጎቶች አይ',
      'choose_role': 'ሚናዎን ይምረጡ',
      'role_explainer': 'ዛሬ ኤይድሊንክን እንዴት መጠቀም እንደምትፈልጉ ይምረጡ።',
      'role_seeker_desc': 'በክብር አስፈላጊ ድጋፍ ይጠይቁ።',
      'role_donor_desc': 'እርዳታ ይስጡ እና አስቸኳይ ፍላጎቶችን ይመልሱ።',
      'role_admin_desc': 'ጥያቄዎችን ያረጋግጡ እና እርዳታን ያቀናብሩ።',
      'choose_role_first': 'ቀጥለው ለመጀመር ሚና ይምረጡ።',
      'continue_with_google': 'በGoogle ቀጥል',
      'enable_biometrics': 'ባዮሜትሪክ ግባ በዚህ መሳሪያ አንቃ',
      'use_biometrics': 'ባዮሜትሪክ ተጠቀም እና ግባ',
      'donor_header_subtitle': 'አስቸኳይ ፍላጎቶችን ይመልከቱ እና ፈጥነው ይርዱ።',
      'seeker_header_subtitle': 'ጥያቄዎችዎን ይከታተሉ እና አዲስ ማስታወቂያዎችን ይቀበሉ።',
      'impact_snapshot': 'የተፅዕኖ ማጠቃለያ',
      'total_requests': 'አጠቃላይ ጥያቄዎች',
      'urgent_requests': 'አስቸኳይ ጥያቄዎች',
      'nearby_requests': 'በአቅራቢያ ያሉ ጥያቄዎች',
      'recent_requests': 'የቅርብ ጥያቄዎች',
      'no_urgent_requests': 'አሁን አስቸኳይ ጥያቄ የለም',
      'my_activity': 'እንቅስቃሴዬ',
      'active_requests': 'በሥራ ላይ ያሉ ጥያቄዎች',
      'no_active_requests': 'አሁን በሥራ ላይ ያለ ጥያቄ የለም',
      'create_request_cta': 'ጥያቄ ፍጠር',
      'seeker_dashboard': 'የእርዳታ ፈላጊ ዳሽቦርድ',
      'donor_dashboard': 'የእርዳታ አቅራቢ ዳሽቦርድ',
      'admin_dashboard': 'የአስተዳዳሪ ዳሽቦርድ',
      'request_types': 'የጥያቄ ዓይነቶች',
      'pending_support': 'በመጠባበቅ ያለ ድጋፍ',
      'delivery_pickup': 'መልቀቅ',
      'delivery_dropoff': 'የተላከ',
      'filters': 'ማጣሪያዎች',
      'history': 'ታሪክ',
      'urgent_actions': 'አስቸኳይ ተግባሮች',
      'admin_tools': 'የአስተዳዳሪ መሳሪያዎች',
      'audit_log': 'የእርምጃ ምዝገባ',
      'status_draft': 'ረቂቅ',
      'status_submitted': 'ተላክ',
      'status_verified': 'ተረጋገጠ',
      'status_matched': 'ተመሳሰለ',
      'status_in_progress': 'በሂደት ላይ',
      'status_completed': 'ተጠናቀቀ',
      'aid_food': 'ምግብ',
      'aid_clothing': 'ልብስ',
      'aid_medical': 'ሕክምና',
      'aid_cash': 'ገንዘብ',
      'aid_school': 'ትምህርት',
      'aid_housing': 'መኖሪያ',
      'aid_ceremony': 'ስነ-ሥርዓት ድጋፍ',
      'aid_other': 'ሌላ',
    },
  };

  static String tr(Locale locale, String key) {
    final lang = locale.languageCode;
    return _strings[lang]?[key] ?? _strings['en']![key] ?? key;
  }
}

